FROM amazon/aws-cli

ARG AWS_ACCESS_KEY_ID=defaultValue
ARG AWS_SECRET_ACCESS_KEY=defaultValue
ARG AWS_DEFAULT_REGION='eu-central-1'

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

RUN aws --version
RUN aws s3 ls
